name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change this to the desired Node.js version

      - name: Build and deploy
        run: |
          npm install  # Or yarn install if you use yarn
          npm run build  # Replace with your build command
          npx gh-pages -d /source  # Replace <build-directory> with the directory containing the built files
