name: Jest Tests

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Jest
        id: jest
        run: npx jest || echo '::set-output name=status::failure'