name: Jest Tests

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Jest
        id: jest
        run: npx jest

      - name: Set Failure Status
        id: set-failure-status
        run: echo "::set-output name=failed::${{ steps.jest.outcome != 'success' }}"

      - name: Fail Workflow
        if: ${{ steps.set-failure-status.outputs.failed == 'true' }}
        run: exit 1