name: Jest Tests

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Start local server
        run: |
          npm run start-server & # Run the server as a background process
          sleep 5 # Give the server time to start
          echo "Local server started"

      - name: Jest
        id: jest
        run: npm run test